name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 触发部署的源分支名称

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # 或者你的 Node.js 版本

    - name: Install dependencies
      run: npm install

    - name: Build static files
      run: npm run docs:build

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd docs/.vuepress/dist
        
        # Debug Git configuration
        echo "Current Git configuration:"
        git config --list
        
        # Configure Git user info globally before initializing the repository
        git config --global user.name "const"
        git config --global user.email "constconst51@gmail.com"
        
        # Initialize Git repository and configure Git user info locally
        git init
        git config user.name "const"
        git config user.email "constconst51@gmail.com"

        # Add and commit changes
        git add -A
        git commit -m 'Deploy to GitHub Pages' || echo "No changes to commit"

        # Push to the GitHub Pages branch
        git push -f https://github.com/dandan228/vue3-eltable-jsx.git main:gh-pages
