name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 触发部署的源分支名称

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # 或者你的 Node.js 版本

    - name: Install dependencies
      run: npm install

    - name: Build static files
      run: npm run docs:build

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd docs/.vuepress/dist
        
        # 配置 Git 用户信息
        git config --global user.name "const"
        git config --global user.email "constconst51@gmail.com"

        # 初始化 Git 仓库
        git init
        
        # 添加所有更改并提交
        git add -A
        git commit -m 'Deploy to GitHub Pages' || echo "No changes to commit"

        # 设置远程仓库 URL（包括 token）
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/dandan228/vue3-eltable-jsx.git

        # 强制推送到 GitHub Pages 分支
        git push -f origin master:gh-pages
